### ISSUE TITLE
Support Centrifugo v2

### ISSUE THREAD

**Issue by FZambia** [centrifugal/rubycent#11]
Does someone interested in migrating this library to support Centrifugo v2? We need 2 things:

* migrate code to work with v2 (I can help explaining differences between v1 and v2 API)
* make automatic releases over travis CI – so creating tag in this lib resulted in automatic uploading of new release to package registry

**Comment by arrowcircle** [comment]
@FZambia Automatic releases on tags are set up. Does they fail to release?

**Comment by FZambia** [comment]
@arrowcircle just did not remember this - if it already works then this is very cool!
