### ISSUE TITLE
JS token generation with info

### ISSUE THREAD

**Issue by gauravtiwari** [centrifugal/rubycent#2]
Hey @FZambia 

Another issue is when generating client JS token using `token_for` method, the subscription works without `info`, but when I add `info` JSON string the channel isn't getting subscribed and throwing "disconnected message". 

![screen shot 2015-08-18 at 13 29 11](https://cloud.githubusercontent.com/assets/771039/9329877/28982b80-45ad-11e5-96d6-0adee3e286ac.png)

Thanks

**Comment by arrowcircle** [comment]
Please post some examples of info json string

**Comment by gauravtiwari** [comment]
@arrowcircle fixed this one too, it was due to wrong JSON generation. I think we need to put some examples here related to ruby code. I will update docs.
