### ISSUE TITLE
Centrifugo js client dosen't work

### ISSUE THREAD

**Issue by Stashchenko** [centrifugal/rubycent#6]
I updated gem to new one after that my app goes down)
With Ruby code everything ok but js has a bug)
It can't work without 'project' property. (207 line)
<img src='http://oi66.tinypic.com/otg6rl.jpg'/>

It call centifugo server every seconds with function that something want to refresh) 
js-api call the same port of my app instead centrifugo server.
I took a js code from: 
https://cdn.jsdelivr.net/sockjs/1.0/sockjs.min.js
https://rawgit.com/centrifugal/centrifuge-js/master/centrifuge.js

And this it works great. 
Please refresh assets in gem.
Thanks.

**Comment by FZambia** [comment]
@Stashchenko hello! Thanks for report.

Personally I had no experience with Ruby and don't know why Ruby client has its own prebuilt assets in gem. Is this a standard practice for Ruby?

I've updated centrifuge.js. @arrowcircle could you help here with release?

**Comment by Stashchenko** [comment]
Hello @FZambia! You are welcome.
Yes, It's standard practice to use assets in gem.

**Comment by Stashchenko** [comment]
And you should change version of gem on 1.0.1. Because bundler can't update this fix. For it it's the same version. I has installed gem of old version(1.0.0) before fix. Ofcourse I can reinstall gem, but only on development machine. In production it's harder). If you change version of gem it'll automatically update on all my machines. It's also good practice in gem development. Especially in this case.
Thanks.

**Comment by arrowcircle** [comment]
@Stashchenko @FZambia Sorry, I totally forgot to update assets for 1.0 version.
Version 1.0.1 is out.

**Comment by FZambia** [comment]
@arrowcircle thanks!
